addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph"    % "0.8.2")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"             % "0.3.0")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"            % "0.6.1")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"           % "1.5.0")
addSbtPlugin("com.updateimpact"  % "updateimpact-sbt-plugin" % "2.1.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"             % "1.0.4")
addSbtPlugin("me.lessis"         % "bintray-sbt"             % "0.3.0")
