addSbtPlugin("com.geirsson"      % "sbt-scalafmt"            % "0.6.8")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"           % "1.5.1")
addSbtPlugin("com.updateimpact"  % "updateimpact-sbt-plugin" % "2.1.2")
addSbtPlugin("com.github.gseitz" % "sbt-release"             % "1.0.5")
addSbtPlugin("me.lessis"         % "bintray-sbt"             % "0.3.0")
